# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BarHopper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BarHopper
	pod ‘Firebase/Core’, ‘~> 5.11.0’
	pod ‘Firebase/Database’

  target 'BarHopperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BarHopper-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BarHopper-tvOS

  target 'BarHopper-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
